### ISSUE TITLE
2nd event with similar start to name doesn't work

### ISSUE THREAD

**Issue by JohnAJ** [jhornsby/djrequestapp#1]
If there's an event, e.g. mddf, and a new event is created mddf2, this 2nd event neither prints from admin or is accessible publically. Perhaps because of the similarity in the names?

**Comment by JTProjectFun** [comment]
There was a duplicate eventkey.  This shouldn't have been possible had the database schema been setup correctly.  Now the database column is set to UNIQUE, but there needs to be error reporting to the admin user that they're trying to create a duplicate.
