### ISSUE TITLE
Sessions already started

### ISSUE THREAD

**Issue by JohnAJ** [jhornsby/djrequestapp#3]
session_start(); is used everywhere, many times when a session may already be started.

To avoid possible warnings / errors, this should be: -

```
if (session_status() == PHP_SESSION_NONE) {
  session_start();
}
```

Which will work OK for PHP >= 5.4.0, but if you want to cater for earlier versions maybe use: -

```
if (session_id() == '') {
  session_start();
}
```

**Comment by JTProjectFun** [comment]
This should be fixed now but I've not yet had a chance to test it all out properly.

**Comment by JTProjectFun** [comment]
Fixed AFAIK
