### ISSUE TITLE
Wrong file name?

### ISSUE THREAD

**Issue by JohnAJ** [jhornsby/djrequestapp#6]
Don't know if it's an issue as I haven't actually tested (still waiting for my NAS upgrade), but I spotted in functions/functions.php: -

`$init = parse_ini_file(dirname(__DIR__).'/config.php');`

shouldn't this be configuration.php ?

**Comment by JTProjectFun** [comment]
This was part of testing abstraction of database functions.  My head's a shed at the moment so it'll be a few days before I look at code again

**Comment by JTProjectFun** [comment]
Closed, as no longer relevant
